---

- name: Update dependencies
  become: true
  apt:
    update_cache: yes

- name: Upgrade dependencies
  become: true
  apt:
    upgrade: yes

- name: Install nodejs
  become: true
  apt:
    name: [nodejs, npm]

- name: Install Python
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present