---

- name: Update dependencies
  become: true
  apt:
    update_cache: yes

- name: Upgrade dependencies
  become: true
  apt:
    upgrade: yes

- name: Install Python
  become: true
  apt:
    name: pm2

- name: Install nodejs
  become: true
  apt:
    name: [nodejs, npm]