---

- name: Create backend Directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: Extract files to backend servers
  become: true
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Install packages from package.json file
  npm:
    global: false
    path: /home/ubuntu/backend

- name: Stop default process
  become: true
  become_method: sudo
  command: pm2 stop default
  args:
    chdir: /home/ubuntu/backend
  register: shell_output

- name: Start pm2 process
  become: true
  become_method: sudo
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/backend
  register: shell_output

- name: Check process status
  become: true
  become_method: sudo
  command: pm2 status
  register: shell_output
  