---

- name: Create backend Directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: Extract files to backend servers
  become: true
  unarchive:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/backend

- name: Install packages from package.json file
  become: true
  become_method: sudo
  become_user: root
  command: npm install
  args:
    chdir: /home/ubuntu/backend


- name: Start pm2 process
  become: true
  become_method: sudo
  become_user: root
  command: pm2 start npm --name "backend" -- run start
  args:
    chdir: /home/ubuntu/backend

- name: Check process status
  become: true
  become_method: sudo
  become_user: root
  command: pm2 status
  