version: 2.1

orbs:
  slack: circleci/slack@4.12.1
  node: circleci/node:4.1

default_frontend: &frontend
  working_directory: ~/UDAPEOPLE/frontend 
  docker:
    - image: circleci/node:13.8.0

default_backend: &backend
  working_directory: ~/UDAPEOPLE/backend
  docker:
    - image: circleci/node:13.8.0


commands:
  install_dependencies:
    parameters:
      repo:
        type: string
        default: UDAPEOPLE
      folder:
        type: string
    steps:
      - checkout:
          path: ~/<<parameters.repo>>
      - restore_cache:
          key: <<parameters.folder>>-build
      - run:
          name: Install <<parameters.folder>> dependencies
          command: npm install


jobs:
  build-frontend:
    <<: *frontend
    steps:
      - install_dependencies:
          folder: frontend
      - run:
          name: Build front-end
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: frontend-build
    
  build-backend:
    <<: *backend
    steps:
      - install_dependencies:
          folder: backend
      - run:
          name: Compile backend
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: backend-build
  
  test-frontend:
    <<: *frontend
    steps:
      - install_dependencies:
          folder: frontend
      - run: 
          name: Run frontend test scripts
          command: npm run test
  
  test-backend:
    <<: *backend
    steps:
      - install_dependencies:
          folder: backend
      - run:
          name: Run test on backend
          command: npm run test

  scan-frontend:
    <<: *frontend
    steps:
      - install_dependencies:
          folder: frontend
      - run:
          name: Fix package vulnerabilities
          command: npm update && npm audit fix --audit-level=critical --force
      - run:
          name: Run audit on frontend.
          command: npm audit --audit-level=critical
  
  scan-backend:
    #<<: *backend
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/backend
          
      - node/install-packages
      #- install_dependencies:
          #folder: backend
      - run: echo $SLACK_DEFAULT_CHANNEL
      - run: echo $SLACK_ACCESS_TOKEN
      # - run: echo $SLACK_ACCESS_KEY
      - run: 
          name: Fix package vulnerabilities
          command: npm update && npm audit fix --audit-level=critical --force
      #- run: npm update mkdirp --depth 2
      - run:
          name: Run audit on backend
          command: npm audit --audit-level=critical
      - slack/notify:
          channel: project
          event: fail
          template: basic_fail_1
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "test my app"
      - run: npm d
      - slack/notify:
          channel: project
          event: fail
          template: basic_fail_1

workflows:
  uda_people_workflow:
    jobs:
      - build-frontend
      - build-backend
      # - test:
      #     context: uda-context
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend: 
          requires: [build-backend]
          context: uda-context