version: 2.1

default_frontend: &frontend
  working_directory: ~/UDAPEOPLE/frontend 
  docker:
    - image: circleci/node:13.8.0

default_backend: &backend
  working_directory: ~/UDAPEOPLE/backend
  docker:
    - image: circleci/node:13.8.0

jobs:
  build-frontend:
    <<: *frontend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: frontend-build
      - run: pwd
      - run:
          name: Install front-end dependencies
          command: npm install
      - run:
          name: Build front-end
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: frontend-build
    
  build-backend:
    <<: *backend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: backend-build
      - run:
          name: Install backend dependencies
          command: npm install
      - run:
          name: Compile backend
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: backend-build
  
  test-frontend:
    <<: *frontend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: frontend-build
      - run: 
          name: Install frontend dependencies
          command: npm install
      - run: 
          name: Run frontend test scripts
          command: npm run test
  
  test-backend:
    <<: *backend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: backend-build
      - run:
          name: Install backend dependencies
          command: npm install 
      - run:
          name: Run test on backend
          command: npm run test

  scan-frontend:
    <<: *frontend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: frontend-build
      - run:
          name: Install frontend dependencies
          command: npm install
      - run:
          name: Run audit on frontend
          command: npm audit --audit-level=critical
  
  scan-backend:
    <<: *backend
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: backend-build
      - run:
          name: Install backend dependencies
          command: npm install
      - run:
          name: Run audit on backend
          command: npm audit --audit-level=critical

workflows:
  uda_people_workflow:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend: 
          requires: [build-backend]