version: 2.1

jobs:
  build-frontend:
    working_directory: ~/UDAPEOPLE/frontend 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: frontend-build
      - run: pwd
      - run: 
          name: Install front-end dependencies
          command: npm install
      - run:
          name: Build front-end
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: frontend-build
    
  build-backend:
    working_directory: ~/UDAPEOPLE/backend
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout:
          path: ~/UDAPEOPLE
      - restore_cache:
          key: backend-build
      - run:
          name: Install backend dependencies
          command: npm install
      - run:
          name: Compile backend
          command: npm run build
      - save_cache:
          paths: [./node_modules]
          key: backend-build


workflows:
  uda_people_workflow:
    jobs:
      - build-frontend
      - build-backend:
          requires: [build-frontend]
